services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SergeDesign\PimcoreCustomTwigBundle\Twig\Extension\TwigBootstrapSvgIcon:
        tags: [ 'twig.extension' ]

    SergeDesign\PimcoreCustomTwigBundle\Twig\Extension\TwigEditmodeLinkToObject:
        tags: [ 'twig.extension' ]

    SergeDesign\PimcoreCustomTwigBundle\Twig\Extension\TwigLanguageSwitcher:
        tags: [ 'twig.extension' ]

    SergeDesign\PimcoreCustomTwigBundle\Twig\Extension\TwigQrCode:
        tags: [ 'twig.extension' ]

    SergeDesign\PimcoreCustomTwigBundle\Twig\Extension\TwigSvgFun:
        tags: [ 'twig.extension' ]

