services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SergeDesign\PimcoreCustomTwigBundle\Twig\Statements\TwigSwitch:
        tags: [ 'twig.extension' ]



