services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SergeDesign\PimcoreCustomTwigBundle\Twig\Test\TwigTests:
    tags:
      - { name: twig.extension }

  SergeDesign\PimcoreCustomTwigBundle\Twig\Test\TwigBundleChecker:
    tags:
      - { name: twig.extension }
    arguments:
      $bundles: '%kernel.bundles%'

